// resources builds a Windows resource object without a C toolchain.
package main

import (
	"encoding/binary"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/akavel/rsrc/rsrc"
)

func main() {
	arch := flag.String("arch", "amd64", "Windows architecture")
	flag.Parse()
	icons := []string{"mitray.ico", "mitray_on.ico", "mitray_off.ico"}
	ids := make([]int, len(icons))
	next := 2 // Manifest consumes resource ID 1.
	for i, name := range icons {
		b, err := os.ReadFile(name)
		if err != nil {
			log.Fatal(err)
		}
		if len(b) < 6 {
			log.Fatal("invalid icon: ", name)
		}
		ids[i] = next
		next += 1 + int(binary.LittleEndian.Uint16(b[4:6]))
	}
	if err := rsrc.Embed("cmd/mitray/rsrc_windows_"+*arch+".syso", *arch, "app.manifest", strings.Join(icons, ",")); err != nil {
		log.Fatal(err)
	}
	code := fmt.Sprintf("// Code generated by tools/resources; DO NOT EDIT.\npackage resources\n\nvar IconIDs = [...]int{%d, %d, %d}\n", ids[0], ids[1], ids[2])
	if err := os.WriteFile("internal/resources/resources.go", []byte(code), 0644); err != nil {
		log.Fatal(err)
	}
}
